title: "Data Analytics Lab"
description: "UNIST Data Analytics Lab"
url: "https://unist-da.github.io"
baseurl: "/heeyoon"

# We won't use a remote theme; keep it simple and custom.
theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  members:
    output: true
    permalink: /members/:name/
  publications:
    output: true
    permalink: /research/:name/

# Navigation (English / Korean)
nav:
  - title: "About"
    url: /about/
  - title: "Members"
    url: /members/
  - title: "Research"
    url: /research/
  - title: "Activity"
    url: /activity/

nav_ko:
  - title: "소개"
    url: /ko/about/
  - title: "구성원"
    url: /ko/members/
  - title: "연구"
    url: /ko/research/
  - title: "활동"
    url: /ko/activity/

lab_name_en: "Data Analytics Lab"
lab_name_ko: "데이터 애널리틱스 연구실"
email: "contact@example.com"
